spring.application.name=BankingSystem
spring.datasource.url=jdbc:postgresql://localhost:5432/bankingsystem
spring.datasource.username=postgres
spring.datasource.password=0968

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true